// Auto-generated IDL for the PhantomZero VRF Sportsbook program
// Program ID: Spo7t11111111111111111111111111111111111111

export const IDL = {
  version: "0.1.0",
  name: "sportsbook",
  instructions: [
    {
      name: "initialize",
      accounts: [
        { name: "bettingPool",  isMut: true,  isSigner: false },
        { name: "authority",    isMut: true,  isSigner: true  },
        { name: "tokenMint",    isMut: false, isSigner: false },
        { name: "protocolTreasury", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "protocolFeeBps",      type: "u16" },
        { name: "winnerShareBps",      type: "u16" },
        { name: "seasonPoolShareBps",  type: "u16" },
      ],
    },
    {
      name: "initializeRound",
      accounts: [
        { name: "bettingPool",     isMut: true,  isSigner: false },
        { name: "roundAccounting", isMut: true,  isSigner: false },
        { name: "authority",       isMut: true,  isSigner: true  },
        { name: "systemProgram",   isMut: false, isSigner: false },
      ],
      args: [{ name: "roundId", type: "u64" }],
    },
    {
      name: "seedRoundPools",
      accounts: [
        { name: "bettingPool",            isMut: true,  isSigner: false },
        { name: "roundAccounting",        isMut: true,  isSigner: false },
        { name: "authority",              isMut: true,  isSigner: true  },
        { name: "authorityTokenAccount",  isMut: true,  isSigner: false },
        { name: "bettingPoolTokenAccount",isMut: true,  isSigner: false },
        { name: "tokenProgram",           isMut: false, isSigner: false },
        { name: "systemProgram",          isMut: false, isSigner: false },
      ],
      args: [{ name: "roundId", type: "u64" }],
    },
    {
      name: "placeBet",
      accounts: [
        { name: "bettingPool",              isMut: true, isSigner: false },
        { name: "roundAccounting",          isMut: true, isSigner: false },
        { name: "bet",                      isMut: true, isSigner: false },
        { name: "bettorTokenAccount",       isMut: true, isSigner: false },
        { name: "bettingPoolTokenAccount",  isMut: true, isSigner: false },
        { name: "protocolTreasuryTokenAccount", isMut: true, isSigner: false },
        { name: "teamTokenAccount",         isMut: false, isSigner: false, isOptional: true },
        { name: "bettor",                   isMut: true,  isSigner: true  },
        { name: "tokenProgram",             isMut: false, isSigner: false },
        { name: "systemProgram",            isMut: false, isSigner: false },
      ],
      args: [
        { name: "roundId",       type: "u64"         },
        { name: "matchIndices",  type: { vec: "u8" } },
        { name: "outcomes",      type: { vec: "u8" } },
        { name: "amount",        type: "u64"         },
      ],
    },
    {
      name: "settleRound",
      accounts: [
        { name: "bettingPool",     isMut: true, isSigner: false },
        { name: "roundAccounting", isMut: true, isSigner: false },
        { name: "authority",       isMut: true, isSigner: true  },
      ],
      args: [
        { name: "roundId",       type: "u64"         },
        { name: "matchResults",  type: { vec: "u8" } },
      ],
    },
    {
      name: "claimWinnings",
      accounts: [
        { name: "bettingPool",             isMut: true,  isSigner: false },
        { name: "roundAccounting",         isMut: true,  isSigner: false },
        { name: "bet",                     isMut: true,  isSigner: false },
        { name: "bettingPoolTokenAccount", isMut: true,  isSigner: false },
        { name: "bettorTokenAccount",      isMut: true,  isSigner: false },
        { name: "claimer",                 isMut: true,  isSigner: true  },
        { name: "claimerTokenAccount",     isMut: true,  isSigner: false },
        { name: "tokenProgram",            isMut: false, isSigner: false },
        { name: "systemProgram",           isMut: false, isSigner: false },
      ],
      args: [
        { name: "betId",     type: "u64" },
        { name: "minPayout", type: "u64" },
      ],
    },
    {
      name: "finalizeRoundRevenue",
      accounts: [
        { name: "bettingPool",     isMut: true, isSigner: false },
        { name: "roundAccounting", isMut: true, isSigner: false },
        { name: "authority",       isMut: true, isSigner: true  },
      ],
      args: [{ name: "roundId", type: "u64" }],
    },
    {
      name: "makeSeasonPrediction",
      accounts: [
        { name: "bettingPool",      isMut: true, isSigner: false },
        { name: "seasonPrediction", isMut: true, isSigner: false },
        { name: "nftMint",          isMut: true, isSigner: true  },
        { name: "userNftAccount",   isMut: true, isSigner: false },
        { name: "user",             isMut: true, isSigner: true  },
        { name: "tokenProgram",     isMut: false, isSigner: false },
        { name: "systemProgram",    isMut: false, isSigner: false },
        { name: "rent",             isMut: false, isSigner: false },
      ],
      args: [{ name: "predictedTeam", type: "u8" }],
    },
    {
      name: "claimSeasonReward",
      accounts: [
        { name: "bettingPool",             isMut: true,  isSigner: false },
        { name: "seasonPrediction",        isMut: true,  isSigner: false },
        { name: "bettingPoolTokenAccount", isMut: true,  isSigner: false },
        { name: "userTokenAccount",        isMut: true,  isSigner: false },
        { name: "user",                    isMut: true,  isSigner: true  },
        { name: "tokenProgram",            isMut: false, isSigner: false },
      ],
      args: [{ name: "totalPredictors", type: "u64" }],
    },
    {
      name: "endSeason",
      accounts: [
        { name: "bettingPool", isMut: true, isSigner: false },
        { name: "authority",   isMut: true, isSigner: true  },
      ],
      args: [{ name: "winningTeam", type: "u8" }],
    },
  ],
  accounts: [
    {
      name: "BettingPool",
      type: {
        kind: "struct",
        fields: [
          { name: "authority",          type: "publicKey" },
          { name: "tokenMint",          type: "publicKey" },
          { name: "protocolTreasury",   type: "publicKey" },
          { name: "liquidityPool",      type: "publicKey" },
          { name: "protocolFeeBps",     type: "u16" },
          { name: "winnerShareBps",     type: "u16" },
          { name: "seasonPoolShareBps", type: "u16" },
          { name: "seasonRewardPool",   type: "u64" },
          { name: "nextBetId",          type: "u64" },
          { name: "nextRoundId",        type: "u64" },
          { name: "teamTokenMints",     type: { array: ["publicKey", 10] } },
          { name: "seasonNftCollection",type: "publicKey" },
          { name: "currentSeasonId",    type: "u64" },
          { name: "seasonEnded",        type: "bool" },
          { name: "seasonWinningTeam",  type: "u8" },
          { name: "bump",               type: "u8" },
        ],
      },
    },
    {
      name: "RoundAccounting",
      type: {
        kind: "struct",
        fields: [
          { name: "roundId",                  type: "u64" },
          { name: "bettingPool",              type: "publicKey" },
          { name: "matchPools",               type: { array: [{ defined: "MatchPool" }, 10] } },
          { name: "lockedOdds",               type: { array: [{ defined: "LockedOdds" }, 10] } },
          { name: "matchResults",             type: { array: [{ defined: "MatchOutcome" }, 10] } },
          { name: "totalBetVolume",           type: "u64" },
          { name: "totalWinningPool",         type: "u64" },
          { name: "totalLosingPool",          type: "u64" },
          { name: "totalReservedForWinners",  type: "u64" },
          { name: "totalClaimed",             type: "u64" },
          { name: "totalPaidOut",             type: "u64" },
          { name: "protocolFeeCollected",     type: "u64" },
          { name: "protocolRevenueShare",     type: "u64" },
          { name: "seasonRevenueShare",       type: "u64" },
          { name: "revenueDistributed",       type: "bool" },
          { name: "protocolSeedAmount",       type: "u64" },
          { name: "seeded",                   type: "bool" },
          { name: "totalUserDeposits",        type: "u64" },
          { name: "parlayCount",              type: "u64" },
          { name: "roundStartTime",           type: "i64" },
          { name: "roundEndTime",             type: "i64" },
          { name: "settled",                  type: "bool" },
          { name: "bump",                     type: "u8" },
        ],
      },
    },
    {
      name: "Bet",
      type: {
        kind: "struct",
        fields: [
          { name: "bettor",          type: "publicKey" },
          { name: "roundId",         type: "u64" },
          { name: "betId",           type: "u64" },
          { name: "amount",          type: "u64" },
          { name: "amountAfterFee",  type: "u64" },
          { name: "allocatedAmount", type: "u64" },
          { name: "bonus",           type: "u64" },
          { name: "lockedMultiplier",type: "u64" },
          { name: "numPredictions",  type: "u8" },
          { name: "predictions",     type: { array: [{ defined: "Prediction" }, 10] } },
          { name: "settled",         type: "bool" },
          { name: "claimed",         type: "bool" },
          { name: "claimDeadline",   type: "i64" },
          { name: "bountyClaimer",   type: { option: "publicKey" } },
          { name: "bump",            type: "u8" },
        ],
      },
    },
    {
      name: "SeasonPrediction",
      type: {
        kind: "struct",
        fields: [
          { name: "user",           type: "publicKey" },
          { name: "seasonId",       type: "u64" },
          { name: "predictedTeam",  type: "u8" },
          { name: "nftMint",        type: "publicKey" },
          { name: "claimedReward",  type: "bool" },
          { name: "predictedAt",    type: "i64" },
          { name: "bump",           type: "u8" },
        ],
      },
    },
  ],
  types: [
    {
      name: "MatchPool",
      type: {
        kind: "struct",
        fields: [
          { name: "homeWinPool", type: "u64" },
          { name: "awayWinPool", type: "u64" },
          { name: "drawPool",    type: "u64" },
          { name: "totalPool",   type: "u64" },
        ],
      },
    },
    {
      name: "LockedOdds",
      type: {
        kind: "struct",
        fields: [
          { name: "homeOdds", type: "u64" },
          { name: "awayOdds", type: "u64" },
          { name: "drawOdds", type: "u64" },
          { name: "locked",   type: "bool" },
        ],
      },
    },
    {
      name: "Prediction",
      type: {
        kind: "struct",
        fields: [
          { name: "matchIndex",        type: "u8"  },
          { name: "predictedOutcome",  type: "u8"  },
          { name: "amountInPool",      type: "u64" },
        ],
      },
    },
    {
      name: "MatchOutcome",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending"  },
          { name: "HomeWin"  },
          { name: "AwayWin"  },
          { name: "Draw"     },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "InvalidAmount",                  msg: "Bet amount must be greater than zero" },
    { code: 6001, name: "InvalidMatchIndex",              msg: "Match index out of bounds (0-9)" },
    { code: 6002, name: "InvalidOutcome",                 msg: "Outcome must be 1, 2, or 3" },
    { code: 6003, name: "RoundNotSeeded",                 msg: "Round has not been seeded" },
    { code: 6004, name: "RoundAlreadySettled",            msg: "Round is already settled" },
    { code: 6005, name: "RoundNotSettled",                msg: "Round has not been settled" },
    { code: 6006, name: "BetAlreadyClaimed",              msg: "Bet already claimed" },
    { code: 6007, name: "NotBettor",                      msg: "Only the bettor can claim within 24h" },
    { code: 6008, name: "OddsNotLocked",                  msg: "Odds not locked for this match" },
    { code: 6009, name: "InsufficientProtocolLiquidity",  msg: "Protocol has insufficient liquidity" },
    { code: 6010, name: "BetExceedsMaximum",              msg: "Bet amount exceeds maximum allowed" },
    { code: 6011, name: "CalculationOverflow",            msg: "Arithmetic overflow in calculation" },
    { code: 6012, name: "ArrayLengthMismatch",            msg: "Match indices and outcomes arrays must be same length" },
    { code: 6013, name: "InvalidBetCount",                msg: "Must bet on 1-10 matches" },
    { code: 6014, name: "PayoutBelowMinimum",             msg: "Payout below minimum slippage protection" },
    { code: 6015, name: "RoundPayoutLimitReached",        msg: "Round maximum payout limit reached" },
    { code: 6016, name: "InvalidRoundId",                 msg: "Round ID must be sequential" },
    { code: 6017, name: "InvalidAuthority",               msg: "Only authority can perform this action" },
    { code: 6018, name: "RevenueDistributedBeforeClaims", msg: "Cannot finalize revenue before claim window expires" },
  ],
} as const

export type SportsbookIDL = typeof IDL
